- Gemfile
- Gemfile.lock
- app/controllers/activities_controller.rb
- app/models/activity.rb
- app/views/activities/index.html.erb
- config/routes.rb
- db/migrate/20210301191958_create_activities.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/activities_controller_test.rb
- test/models/activity_test.rb
Creé modelo y controlador de activities, junto con view y action de index. También puse 3 seeds de actividades y usé la gema pg-search para hacer el buscador
> Activities index

- app/assets/stylesheets/components/_cards.scss
- app/views/shared/_cards.html.erb
Hice las primeras 4 cards del ui kit, voy a tratar de dejarles una captura de pantalla para que sepan a que correspponde.
> first components for the ui kit

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
- db/schema.rb
Puse la nueva navbar con sus cambios cuando el user esta logueado. Aun estoy trabajando con el footer
> big changes in navbar

- app/assets/stylesheets/pages/_activity-show.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/activities_controller.rb
- app/views/activities/show.html.erb
- db/schema.rb
Listas la acción del controller de show + la vista correspondiente. Los botones por ahora están hardcodeados, cuando avancemos un poco más vamos a tener que volver a poner los links que corresponden. En cuanto a los estilos, me basé en lo que teníamos en el Figma y seguí usando escala de grises hasta que definamos la paleta de colores a usar.
> Activity show

- app/assets/stylesheets/pages/_activity-show.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/activities_controller.rb
- app/models/activity.rb
- app/models/chatroom.rb
- app/models/event.rb
- app/views/activities/show.html.erb
- db/schema.rb
Agrega simples validaciones de presence a los campos de los modelos.
> Validaciones

- db/seeds.rb
Added user seeds, 3 more chatroom seeds and 3 more event seeds
> Adding user seeds

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/javascript/packs/application.js
- app/javascript/plugins/hoverable_menu.js
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
Change padding, add dropdown hoverable and change variables colors
> Navbar improvement

- config/cable.yml
Me faltaba agregar unas cositas de configuración para que funcione el chat en producción
> adds chatroom config for production

- db/migrate/20210303143601_remove_address_from_activities.rb
- db/migrate/20210303143740_add_zone_to_activities.rb
- db/migrate/20210303143809_add_address_to_events.rb
- db/schema.rb
- db/seeds.rb
La tabla activities ahora tiene una columna zone y la tabla events una columna address. Corregí las seed con esos cambios para que no haya problemas!
> makes db changes and fix seeds

- app/views/activities/index.html.erb
- app/views/activities/show.html.erb
Al hacer cambios en la db, se rompía el código en algunos lugares, creo que ya están corregidos
> fixs errors

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/views/chatrooms/show.html.erb
- app/views/shared/_footer.html.erb
I change the bottom of the footer and also deleted a spare `</div>` from chatroom's show
> chatrooms show and footer fixed

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_cards.scss
- app/controllers/application_controller.rb
- app/controllers/users/registrations_controller.rb
- app/models/user.rb
- app/views/shared/_navbar.html.erb
- app/views/user_interests/index.html.erb
- app/views/users/registrations/edit.html.erb
- app/views/users/registrations/new.html.erb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20210304113648_create_active_storage_tables.active_storage.rb
- db/schema.rb
Agrege la posibilidad de editar el perfil desde una opcion en el navbar y desde la eleccion de intereses. En la opcion profile del navbar x ahora direcciona a elegir y editar intereses. agregue tambien la posibilidad de agregar una foto a cloudinary en el sing up y en el edit.
> Edit profile

- app/assets/stylesheets/pages/_event-show.scss
- app/views/events/show.html.erb
added links, frontend and icons with event info
> Flow frontend to event show

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_navbar.scss
- app/javascript/packs/application.js
- app/javascript/plugins/clickable_faq_icon.js
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
navbar responsive (missing a menu and avatar issue), faq functionality (not finished), link to activty_index
> Links, navbar responsive and faq functionality

- app/assets/stylesheets/pages/_event-show.scss
- app/views/shared/_navbar.html.erb
margin top wrong specified and navbar fixed
> problems solved

- app/controllers/events_controller.rb
- app/controllers/participants_controller.rb
- app/views/events/show.html.erb
- config/routes.rb
added new and create function to participants
> Adding new create to participants

- db/seeds.rb
Arreglé algunas cosas de las seed porque tiraba error
> fixs seeds errors

- db/migrate/20210305122513_change_content_type_in_messages.rb
- db/schema.rb
Solucionado el problema del chatroom, lo había roto yo cuando cambié que el content de los messages sea text y no string, así que ahora volví a ponerlo string y funciona :)
> fixs chatroom

- app/controllers/activities_controller.rb
- app/views/activities/show.html.erb
added links to chatroom in activity show that create a chatroom participant and redirect to a particular event's chatroom
> added join chatroom to activity show

- app/controllers/chatrooms_controller.rb
- app/controllers/events_controller.rb
- app/views/chatrooms/new.html.erb
- app/views/events/new.html.erb
arreglé el tema de los errores de users
> fix errors

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_small-cards.scss
- app/assets/stylesheets/pages/_chatroom.scss
- app/controllers/users/registrations_controller.rb
- app/views/activities/show.html.erb
- app/views/chatrooms/new.html.erb
- app/views/chatrooms/show.html.erb
- app/views/events/new.html.erb
hice cmabios grandes en el font de el chat y algunos detalles en otros lados, creo que sin querer cambie el titulo de el activity show y me gustaba.
> changes in show and new chatroom views

- app/views/users/registrations/new.html.erb
solo agregue mas campos al formulario de sing up,
> changes in sing up form

- app/controllers/users/registrations_controller.rb
- app/views/chatrooms/show.html.erb
- app/views/users/registrations/edit.html.erb
- app/views/users/registrations/new.html.erb
solo agregue photo en la card de usuario en el chat show
> User photo in chat

- app/assets/stylesheets/pages/_home.scss
- app/views/activities/index.html.erb
Autocompletado para la búsqeuda de actividades en activities#index
> adds autocomplete to activities#index

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- db/migrate/20210309142958_add_description_to_users.rb
- db/schema.rb
Hice al migración para agregar description y lo agregué en el users#new y users#edit. Además agregué un condicional para mostrar la foto de usuario si es que la tiene en el users#edit así no se rompe el código si no tiene foto
> adds description to users#new and users#edit

- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index_page.scss
- app/views/activities/index.html.erb
Ahora tienen funcionalidad ambas search bars, le puse algunos estilos y le agregué un mensaje cuando no aparece nada en la búsqueda para que no quede en blanco solamente
> fixs search bar and styles

- app/controllers/chatrooms_controller.rb
- app/controllers/participants_controller.rb
- app/models/user.rb
- app/views/chatrooms/new.html.erb
I modified the label_method instead of the user collection at new_chatroom
> Fixing invitations

- app/assets/stylesheets/pages/_index_page.scss
- app/views/activities/index.html.erb
Agregué comportamiento responsive a la search bar de activities#index. MIREN ANTES DE MERGEAR NO CONFÍEN EN SANTI
> adds responsive behaviour to the search bar

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
fix right corner buttons and the sizes with the links to be reponsive
> spacing issues fixed

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
change some font-size issues of h1 and styles of the search bar
> Banner improvements

- db/seeds.rb
generate users-seeds missing and relate each user to some (interests for user, activities for us)
> interests related to users - seeds

- app/controllers/activities_controller.rb
just showing all activities if a user does not have any interest
> Showing activities if any interest

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
> Footer improvements

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_cards.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
improve cards grid, changing spacing
> change grid details and spacing

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
> Search bar improvements

- app/assets/stylesheets/components/_cards.scss
Solucionados los problemas con media query, deberia verse proporcionada las fotos y responsive
> problems with media-query solved

- app/assets/stylesheets/pages/_event-show.scss
- app/views/events/show.html.erb
Agergué una foto de placeholder, puse fondo blanco como dijo Feli. Fijense si les copa, la parte estética claramente no es lo mío
> adds photo placeholder and styles

- app/assets/stylesheets/pages/_participant-index.scss
- app/views/participants/index.html.erb
Mayor font weight para el título y el link de show activity abre en una pestaña nueva.
> styles and new tab for link

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_interests.scss
- app/assets/stylesheets/pages/_user-interests.scss
- app/controllers/events_controller.rb
- app/views/events/index.html.erb
- app/views/shared/_navbar.html.erb
grid for events-card an basic styling of the view
> Events index frontend

- app/assets/stylesheets/pages/_activity-show.scss
- app/assets/stylesheets/pages/_new-chatroom.scss
- app/views/activities/show.html.erb
- app/views/chatrooms/new.html.erb
Cambió el texto del párrafo y el tema del responsive, ahora para tamaños md hay dos cards por fila, y agrandé una columna más para tamaños xl así se diferencia mejor
> Chatroom#new style

- app/assets/stylesheets/pages/_event-show.scss
- app/assets/stylesheets/pages/_users-show.scss
- app/views/activities/show.html.erb
- app/views/devise/show.html.erb
Arregle las event cards del user show y modifique el responsiveness
> Change user show event cards

- app/assets/stylesheets/pages/_users-form.scss
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_forgotpass.html.erb
- app/views/devise/shared/_signup.html.erb
Moví el link de forgot password abajo del input de password y el botón de sign up al costado del de login con un texto. Para eso tuve que crear dos archivos nuevos en la carpeta devise/shared para poder renderizarlos individualmente.
> Login frontend

- app/assets/stylesheets/components/_buttons.scss
- app/views/events/show.html.erb
- db/seeds.rb
FInish seeds with participants, add styling missing to some views
> User and chatrooms seeds

- app/assets/stylesheets/pages/_home.scss
- app/views/activities/index.html.erb
- app/views/activities/show.html.erb
- app/views/chatrooms/new.html.erb
- app/views/chatrooms/show.html.erb
- app/views/devise/show.html.erb
- app/views/events/index.html.erb
- app/views/events/show.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/participants/index.html.erb
- app/views/user_interests/index.html.erb
- config/meta.yml
- db/seeds.rb
meta-image fixed and meta-title/description added to main views
> Meta data views

- app/assets/stylesheets/components/_message.scss
- app/assets/stylesheets/pages/_chatroom.scss
- app/views/chatrooms/show.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/messages/_message.html.erb
fronte end de chatroom show, solo me falto que quede pegado al navbar el chat cuando hacemos scroll
> Chatroom show

- app/views/devise/show.html.erb
Arregle el link para editar el perfil
> fixed profile edit link

- app/views/activities/index.html.erb
- app/views/shared/_footer.html.erb
error with meta data title fixed in home and footer bottom improved
> Debugging search bar home

- app/assets/stylesheets/components/_message.scss
- app/assets/stylesheets/pages/_chatroom.scss
- app/views/chatrooms/show.html.erb
- app/views/messages/_message.html.erb
- app/views/shared/_footer.html.erb
le arregle lo que habiamos visto del user name, las sombras y algunos colorcitos, la voy subiendo por si le quieren hacer algo mas
> Sticky chatroom

- app/assets/stylesheets/components/_cards.scss
- app/views/events/show.html.erb
Fixed private chatroom link on event show and activity index card photo style
> Fix private chatroom link

- app/views/activities/index.html.erb
make img of index act clickable, but not cards
> Cards as buttons

- app/assets/stylesheets/components/_message.scss
- app/assets/stylesheets/pages/_chatroom.scss
- app/views/chatrooms/show.html.erb
- app/views/shared/_footer.html.erb
improving style and responsiveness
> Chatroom colors
